// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssvzjacitrjvndkgrfns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzdnpqYWNpdHJqdm5ka2dyZm5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNjAwNjEsImV4cCI6MjA1ODgzNjA2MX0.qZXu_lNEvCFQM3vdfWadoRxceGPvmkbORQx8YdSfUIE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);